### PR TITLE
Fix: Ignoring time interval on DefaultLocationProvider

### LINKED ISSUE #116: location fetching every second
In Emulator testing for Kitkat and Lollipop
- When GooglePlayServices isn't present DefaultProvider is used

#### Issue
- `onLocationChanged` getting triggered every second for `keepTracking(true)`

#### below is my configuration
` 

                val trackingDistance = 500f
                val interval = 10000

                val locationRequest = LocationRequest.create()
                    .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
                    .setInterval(interval)
                    .setFastestInterval(interval)
                    .setSmallestDisplacement(trackingDistance)

                val googleServiceConfiguration = GooglePlayServicesConfiguration.Builder()
                    .locationRequest(locationRequest)
                    .fallbackToDefault(true)
                    .ignoreLastKnowLocation(true)
                    .setWaitPeriod(TWO_SECONDS)
                    .build()

                val defaultProviderConfiguration = DefaultProviderConfiguration.Builder()
                    .requiredTimeInterval(interval)
                    .requiredDistanceInterval(trackingDistance.toLong())
                    .acceptableAccuracy(5.0f)
                    .acceptableTimePeriod(FIVE_MINUTE)
                    .setWaitPeriod(ProviderType.GPS, TWO_SECONDS)
                    .build()

                val awesomeConfiguration = LocationConfiguration.Builder()
                    .keepTracking(true)
                    .useGooglePlayServices(googleServiceConfiguration)
                    .useDefaultProviders(defaultProviderConfiguration)
                    .build()

                locationManager = LocationManager.Builder(applicationContext)
                    .configuration(awesomeConfiguration)
                    .notify(this)
                    .build()`

### PR DESCRIPTION
**Pull request by yayaa**
Fixes #116

### CODE REVIEW

File: library/src/main/java/com/yayandroid/locationmanager/providers/locationprovider/DefaultLocationProvider.java [hunk 1]
```diff
@@ -224,11 +227,9 @@ public void onLocationChanged(Location location) {
             getSourceProvider().getProviderSwitchTask().stop();
         }
 
-        getSourceProvider().removeLocationUpdates(this);
-
-        if (getConfiguration().keepTracking()) {
-            requestUpdateLocation(getConfiguration().defaultProviderConfiguration().requiredTimeInterval(),
-                  getConfiguration().defaultProviderConfiguration().requiredDistanceInterval(), false);
+        if (!getConfiguration().keepTracking()) {
```
Comment (yayaa) [inline library/src/main/java/com/yayandroid/locationmanager/providers/locationprovider/DefaultLocationProvider.java:230]: Instead of removing and registering new requests, only remove if keepTracking is false
